benaclejames/VRCFaceTracking

README.md
VRCFaceTracking/Params/EyeTrackingParams.cs

This PR adds support for CombinedEyeLid properties. The main reason I added this, is because I was working with an avatar that used textures for it's eyes and I wanted to save parameter storage, so instead of using both Left and Right Eyelid as conditions in the animator controller, I added CombinedEyeLid. There's both the float and bool parameter support, just like the current Left and Right Eyelid parameters.
The math is just `(LeftEyeLid + RightEyeLid)/2` and if it's a bool parameter, it adds `< 0.5f`. There is native CombinedEyeLid data with the v2 eye data, but I can't get it to work for me (I think an HMD issue) and this would mathematically be the same.
File Changes:
+ `Params/EyeTrackingParams.cs`
+ Added "CombinedEyeLid" as a `FloatEyeParameter`
+ This gets v2 data to add both …

Add CombinedEyeLid

---

VRCFaceTracking/Params/Lip/LipShapeConversion.cs
VRCFaceTracking/Params/Lip/LipShapeMerger.cs

Many people seem to be using only 1 side of the combined params to power both sides, which isnt ideal for some params. This PR creates new combined params that average the left and right side for these, which should give more consistent resullts across different users. Its possible taking the biggest param (math.max) would be better than taking the avereage for some of these
There is some similar code implemented in #72 for combining/averaging shapes also.

Implement combined left/right params

---

.github/workflows/build.yml

This is a GitHub Action that triggers on new pushes and pull requests.
It builds the OSC app in both Debug and Release modes, and uploads the result as an artifact.
The commit gets marked with a tick or cross based on whether the build succeeds, so you can check the logs if something fails.
The artifact is downloadable, so it gives quick access to a debug and release exe & pdb on each commit.
Doesn't handle the example module since that depends on the mod, but can be adjusted to target another csproj or the sln if it gets updated.

GitHub Actions workflow for automatic binary builds

---

VRCFaceTracking/UnifiedLibManager.cs

Was quite handy to find out why VRCFTVarjoModule wasn't working (the recent Interface changes)

Adding error message when loading an external module fails

---

VRCFaceTracking/UnifiedLibManager.cs

Turns out that the function throwing the reflection exception was GetTypes, not LoadFrom

Moving try/catch so that it's actually useful.

---

VRCFaceTracking/Assets/UI/MainWindow.xaml.cs

I found an issue regarding higher memory consumption with a lot of unncessary GC activity while using the cutting edge build of VRCFT with a Varjo module that supplies camera data to the app. The issue is most noticeable when a module provides a high-resolution image - I know that VRCFT doesn't need such an high-res image but the issue still persits

Reduce memory consumption when working with large camera images

---

VRCFaceTracking/Params/Eye/EyeTrackingParams.cs
VRCFaceTracking/Params/Lip/LipShapeMerger.cs
VRCFaceTracking/UnifiedTrackingData.cs

These are bool parameters that are set true when the respective type of tracking is active. This allows avatars to detect when tracking is available for use and to react appropriately.
I've tested these with a Vive Pro Eye and the Vive Face Tracker, it accurately detects when the lip tracker is not enabled/tracking as well as turns on/off as appropriate when the hardware isn't present.
I've only added the functionality for one avatar to the eyes to enable/disable tracking with the new parameter, but it worked flawlessly along with an override bool toggle in the expressions menu.
Challenges:
- The VRCFT application does not seem to be able to detect if the face tracker is unplugged and does not set the parameter to false
- Any update that adds new parameters will require users to flush …

Add EyeTrackingActive and LipTrackingActive parameters

---

VRCFaceTracking/UnifiedTrackingData.cs

- Prior to this commit, EyesDilation has a lower bound of `1 / (max - min)` meaning it can never be 0, and EyesDilation may be greater than 1 if the dilation is greater than `(max - min) * min`, causing it to possibly saturate early.
- This commit changes the formula to a ramp so that the value of EyesDilation will be 0 when the dilation is equal to min, and 1 when the dilation is equal to max.

Change EyesDilation formula:

---

VRCFaceTracking/Params/Eye/EyeTrackingParams.cs
VRCFaceTracking/UnifiedTrackingData.cs

- Expose pupil diameter as EyesPupilDiameter to provide tighter control for avatar owners. The existing parameter, EyesDilation, relies on historical eye diameter data acquired since the last avatar change to determine the minimum and maximum eye dilation, which can vary depending on the recent user activity, calibration error, and lighting conditions.
This makes it difficult to create an eye representation using EyesDilation that best reflect physiological effects that the user may be experiencing during a specific session.
- Due to a lack of available information regarding the iris size on the Vive Pro Eye, the currently exposed diameter is in an absolute unit rather than relative. Exposing other parameters leveraging on other APIs such as the Varjo Aero is out of scope here.
- A pupil …

Expose pupil diameter from 0 to 1 cm

---

VRCFaceTracking/UnifiedLibManager.cs
VRCFaceTracking/Utils.cs

That PR is going to fix the main issue of many first time users of custom VRCFT modules that is forgetting to unblock the downloaded module. Yay

Start automatically removing 'downloaded from the internet' identifiers from custom modules

---

VRCFaceTracking/ArgsHandler.cs
VRCFaceTracking/MainStandalone.cs
VRCFaceTracking/UnifiedLibManager.cs

Adds --disable-eye and --disable-lip which are passed to the tracking module to disable loading of each respectively if not needed.
For reference this is because I've had an eye surgery and I would like to be able to use the lip tracker without my eye tracker firing up and shooting IR into my recovering eye, but I figured generalizing this might be useful to others.

Add command line arguments to disable eye/lip tracking

---

VRCFaceTracking.Core/Params/Expressions/UnifiedExpressionsMerger.cs

Pretty self explanatory, simply removes all plural naming in combined parameters for v2.
Example for BrowDown expressions:
``` 
BrowDown -> BrowDownRight
-> BrowDownLeft
```
This forces all parameters to not only be consistent in the naming convention, but also to follow a naming convention now. I hope this change reduces ambiguity when picking combined parameters in v2 parameters!
I do not believe this will affect many people, since most people are still currently on legacy parameters

Plural Be Gone! (Removed all plural naming in v2 combined parameters)

---

.gitignore
VRCFaceTracking/Strings/en/Resources.resw
nuget.config

- Added spaces to the English translation file for the module registry page where applicable.
- Added the external package repository "CommunityToolkit-Labs" to nuget.config to ease in setting up a proper build environment.
- Added VSCode to the .gitignore.

[v5.0.0] Module Registry naming fixes, Addition of a proper `nuget.config`, and VSCode `.gitignore` inclusion

---

VRCFaceTracking.Core/Params/Expressions/UnifiedExpressionsMerger.cs

As part of the larger Lip -> Expression update
Seem to have been missed in the overall update, I know the special case handling the parameter changing in game making it back to VRCFT is commented out for now but that was the only place I could find it actually in the code, so this should be what's needed to have it actually function.
Of note also ExpressionTrackingActive would then also need to be on [the wiki docs](https://github.com/benaclejames/VRCFaceTracking/wiki/Parameters).

Add ExpressionTrackingActive

---

VRCFaceTracking.Core/Utils.cs
VRCFaceTracking.Core/VRChat.cs

Should address the issues with Appdata using the folder in Packages in addition to the Appdata/Roaming folder.
Appdata/LocalLow change prevents extremely rare crash when user for some reason has their Roaming folder and Local/LocalLow folders in separate drives..

use system environment variable for Appdata and Appdata/LocalLow

---

VRCFaceTracking/Views/SettingsPage.xaml.cs

This PR fixes issues with the incomplete code for handling debug streams from HMDs. I have tested this with the Vive facial tracker but don't have a suitable eye tracker to test with.
Should be robust enough to handle devices changing during runtime, but I haven't had time to extensively test this yet.

Fix incomplete code for handling debug camera streams

---

VRCFaceTracking.Core/Params/Expressions/UnifiedExpressionsParameters.cs

Changed 
v2/MouthTightenStretch/Left/Right to
v2/MouthTightenerStretch/Left/Right for consistency with existing v2/MouthTightener parameter
Nice catch jerry

Parameter name consistency fix

---

VRCFaceTracking/Views/SettingsPage.xaml
VRCFaceTracking/Views/SettingsPage.xaml.cs

This PR does two changes:
1. Fixes a crash that could occur when shutting down VRCFT on the settings page.
2. Fixes the Hardware Debug Streams panel using more spacing than necessary when using HMDs with either zero or one debug stream (eg using a Quest Pro, or only a Vive Facial Tracker)

Settings improvements

---

VRCFaceTracking.Core/Params/Data/UnifiedTrackingMutator.cs

Added explicit corrections pass to unified expressions mutations to ensure certain parameters aren't driven past their physical limits.
Currently this just ensures that MouthClosed can never be a lower value than JawOpen
Requested by @Adjerry91

fix(mutator): Added explicit corrections pass to unified expressions

---

VRCFaceTracking/Services/ActivationService.cs

Simple as the title suggests. Changes registry activation behavior to prevent local modules being overwritten in the case that they have a higher version number, as opposed to a different version regardless of higher versioning or not.

Prevent newer (unreleased) Local Modules being overwritten by Registry.

---

VRCFaceTracking.Core/OSC/DataTypes/BinaryBaseParameter.cs

Adjusts a probable oversight where Binary Parameter bits would always round down to now be based on the midpoint of the parameter bit.
Changed function:
```c#
// BinaryBaseParameter.cs
var adjustedValue = Math.Abs(value);
```
To:
```c#
// BinaryBaseParameter.cs
var adjustedValue = Math.Abs(value) + (1f / _maxPossibleBinaryInt);
```
Resolves #241

Adjust Binary Parameter values to be rounded by midpoint.

---

VRCFaceTracking.Core/Models/OscTarget.cs
VRCFaceTracking.Core/Services/OscRecvService.cs
VRCFaceTracking.Core/Services/OscSendService.cs
VRCFaceTracking.Core/Validation/ValidIpAddressAttribute.cs
VRCFaceTracking/Views/SettingsPage.xaml

When changing the ip address or port number to an invalid value on the next restart the app would crash do to the loaded invalid value'(s),
This pull requests checks if: the ip address is not blank or white space, the ip is an valid ip address, it is a resolvable hostname.
It also checks if the ports are not smaller than 1.
Let me know if the code needs any modifications.

Fixed crash on invalid ip and or port change

---

VRCFaceTracking.Core/AvatarConfigFileParser.cs
VRCFaceTracking.Core/OscQueryConfigParser.cs
VRCFaceTracking.Core/Params/Data/Mutation/Filter.cs
VRCFaceTracking.Core/Params/Data/Mutation/ParameterAdjustment.cs
VRCFaceTracking.Core/Params/Data/UnifiedData.cs
VRCFaceTracking.Core/Params/Expressions/UnifiedHeadParameters.cs
VRCFaceTracking.Core/Services/ParameterSenderService.cs
VRCFaceTracking.Core/UnifiedTracking.cs

Gives VRCFT the ability to support desktop "VTubing" using specially set-up avatars with 6 new internal parameters
```
v2/Head/Yaw
v2/Head/Pitch
v2/Head/Roll
v2/Head/PosX
v2/Head/PosY
v2/Head/PosZ
```
Any "desktop" face-tracking application already provides at least rotation data, and existing modules can easily be adapted to provide these data points. 
Example videos: 
https://github.com/user-attachments/assets/61fab05c-f269-427f-94e8-7d72b0caf3ea
---
https://github.com/user-attachments/assets/314e3d36-930e-4a9e-aa67-2e4197f5de39

Add head tracking data support

---

VRCFaceTracking.Core/Params/Data/Mutation/ParameterAdjustment.cs

fix(mutator): Fix MouthOpen not animating lower left side with parameter adjustments

---

VRCFaceTracking.Core/Params/Expressions/UnifiedExpressionsParameters.cs

no more will I go cross-eyed when someone walks in-front of me!
testing this on a Vive pro eye seems to work pretty well
the old ray-casting behavior can still be enabled from the in-game settings menu too

individual eye gaze directions when using built-in eye tracking

---

VRCFaceTracking.Core/Helpers/HappyEyeballs.cs
VRCFaceTracking.Core/Services/ModuleInstaller.cs
VRCFaceTracking.Core/mDNS/MulticastDnsService.cs
VRCFaceTracking/Services/GithubService.cs
VRCFaceTracking/Services/ModuleDataService.cs

This PR tries to fix three common crashes I've seen users encounter on Discord.
1. [C#'s HttpClient does not fall back to IPv4](https://github.com/dotnet/runtime/issues/26177) if it fails to establish an IPv6 connection ("happy eyeballs"). On a poorly configured network, where the user's router provides their PC an IPv6 address, and their DNS provides an AAAA record, but they are unable to connect to an IPv6 host, this causes HttpClient to stall for 100 seconds before raising an exception. This is, unfortunately, very common. ~~An ideal solution would be to attempt to connect to IPv6, then fallback to IPv4. This PR just forces IPv4.~~ This PR now includes proper IPv6 -> IPv4 failover.
2. VRCFT often crashes when trying to setup multicast on VPN or VMware/Hyper-V/etc network adapters. …

Fixes for network-related crashes (IPv6, VPN, multiple addresses)
